import tokens from "./tokens";
import addresses from "constants/addresses";

export const liquidityList = [
  {
    pid: 0,
    lpSymbol: tokens.wild.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.wild.address,
    decimals: 18,
    logoA: tokens.wild.logo,
    logoB: "",
  },
  {
    pid: 0,
    lpSymbol: tokens.eth.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.eth.address,
    decimals: 18,
    logoA: tokens.eth.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: tokens.weth.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.weth.address,
    decimals: 18,
    logoA: tokens.weth.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: "WETH-XXWiLD",
    isTokenOnly: false,
    lpAddresses: addresses.wildWethlp,
    decimals: 18,
    logoA: tokens.wild.logo,
    logoB: tokens.weth.logo,
  },
];

export const zapList = [
  {
    pid: 0,
    lpSymbol: tokens.wild.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.wild.address,
    decimals: 18,
    logoA: tokens.wild.logo,
    logoB: "",
  },
  {
    pid: 0,
    lpSymbol: tokens.eth.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.eth.address,
    decimals: 18,
    logoA: tokens.eth.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: tokens.weth.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.weth.address,
    decimals: 18,
    logoA: tokens.weth.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: tokens.usdc.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.usdc.address,
    decimals: 6,
    logoA: tokens.usdc.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: tokens.dai.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.dai.address,
    decimals: 18,
    logoA: tokens.dai.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: tokens.mim.symbol,
    isTokenOnly: true,
    lpAddresses: tokens.mim.address,
    decimals: 18,
    logoA: tokens.mim.logo,
    logoB: "",
  },
  {
    pid: 1,
    lpSymbol: "WETH-XXWiLD",
    isTokenOnly: false,
    lpAddresses: addresses.wildWethlp,
    decimals: 18,
    logoA: tokens.wild.logo,
    logoB: tokens.weth.logo,
  },
];

const farmsConfig = [
  {
    pid: 0,
    lpSymbol: "WETH-XXWiLD",
    lpAddresses: addresses.wildWethlp,
    isTokenOnly: false,
    isNFTPool: false,
    token: tokens.wild,
    quoteToken: tokens.weth,
    logoA: tokens.wild.logo,
    logoB: tokens.weth.logo,
  },
  {
    pid: 1,
    lpSymbol: "WETH-USDC",
    lpAddresses: addresses.usdcLp,
    isTokenOnly: false,
    isNFTPool: false,
    token: tokens.usdc,
    quoteToken: tokens.weth,
    logoA: tokens.weth.logo,
    logoB: tokens.usdc.logo,
  },
  {
    pid: 2,
    lpSymbol: "WETH",
    lpAddresses: addresses.weth,
    isTokenOnly: true,
    isNFTPool: false,
    token: tokens.weth,
    quoteToken: tokens.weth,
    logoA: tokens.weth.logo,
    logoB: tokens.weth.logo,
  },
  {
    pid: 3,
    lpSymbol: "DAI",
    lpAddresses: addresses.dai,
    isTokenOnly: true,
    isNFTPool: false,
    token: tokens.dai,
    quoteToken: tokens.dai,
    logoA: tokens.dai.logo,
    logoB: tokens.dai.logo,
  },
  {
    pid: 4,
    lpSymbol: "USDC",
    lpAddresses: addresses.usdc,
    isTokenOnly: true,
    isNFTPool: false,
    token: tokens.usdc,
    quoteToken: tokens.usdc,
    logoA: tokens.usdc.logo,
    logoB: tokens.usdc.logo,
  },
  {
    pid: 5,
    lpSymbol: "MIM",
    lpAddresses: addresses.mim,
    isTokenOnly: true,
    isNFTPool: false,
    token: tokens.mim,
    quoteToken: tokens.mim,
    logoA: tokens.mim.logo,
    logoB: tokens.mim.logo,
  },
  {
    pid: 6,
    lpSymbol: "XXWiLDNFT",
    lpAddresses: addresses.nft,
    isTokenOnly: true,
    isNFTPool: true,
    token: tokens.nft,
    quoteToken: tokens.wild,
    logoA: "/assets/tokens/nft.png",
    logoB: "",
  },
];

export default farmsConfig;
